export { default as ArrowForwardFilledIcon } from "./arrowForwardFilled.svg"
export { default as ExpandFilledIcon } from "./expandFilled.svg"
export { default as HomeIcon } from "./home.svg"
export { default as InfoOutlinedIcon } from "./infoOutlined.svg"
export { default as RobotIcon } from "./robot.svg"
export { default as WBLogoIcon } from "./wbLogo.svg"
