/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { animated } from "@react-spring/three"
import { useGLTF } from "@react-three/drei"
import type { RobotModelProps } from "./types"

FANUC_LR_Mate_200iD4S.config = {
  rotationOffsets: [0, Math.PI / 2, 0, 0, 0, 0],
}

export function FANUC_LR_Mate_200iD4S({
  modelURL,
  flangeRef,
  ...props
}: RobotModelProps) {
  const { nodes, materials } = useGLTF(modelURL) as any
  return (
    <group {...props} dispose={null}>
      <group name="Empty">
        <mesh
          name="link_0"
          geometry={nodes.link_0.geometry}
          material={materials.fanuc_metal_black}
        />
        <animated.group name="FANUC_LRMATE200ID4S_J00">
          <animated.group
            name="FANUC_LRMATE200ID4S_J01"
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <animated.group
              name="FANUC_LRMATE200ID4S_J02"
              position={[0.26, 0, 0]}
            >
              <animated.group
                name="FANUC_LRMATE200ID4S_J03"
                position={[0.02, 0, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <animated.group
                  name="FANUC_LRMATE200ID4S_J04"
                  position={[0, -0.29, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <animated.group
                    name="FANUC_LRMATE200ID4S_J05"
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <group
                      name="FANUC_LRMATE200ID4S_FLG"
                      position={[0, -0.07, 0]}
                      rotation={[-Math.PI, 0, 0]}
                    />
                    <mesh
                      name="link_6"
                      geometry={nodes.link_6.geometry}
                      material={materials.fanuc_metal_black}
                      position={[-0.28, 0.29, 0]}
                      rotation={[0, 0, -Math.PI / 2]}
                    />
                  </animated.group>
                  <mesh
                    name="link_5"
                    geometry={nodes.link_5.geometry}
                    material={materials.fanuc_yellow}
                    position={[-0.28, 0, -0.29]}
                    rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  />
                </animated.group>
                <group
                  name="link_4"
                  position={[-0.28, 0, 0]}
                  rotation={[0, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="J3ARM_UNIT"
                    geometry={nodes.J3ARM_UNIT.geometry}
                    material={materials.fanuc_yellow}
                  />
                  <mesh
                    name="J3ARM_UNIT_1"
                    geometry={nodes.J3ARM_UNIT_1.geometry}
                    material={materials.fanuc_aluminium_black}
                  />
                </group>
              </animated.group>
              <mesh
                name="link_3"
                geometry={nodes.link_3.geometry}
                material={materials.fanuc_yellow}
                position={[-0.26, 0, 0]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              />
            </animated.group>
            <mesh
              name="link_2"
              geometry={nodes.link_2.geometry}
              material={materials.fanuc_yellow}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            />
          </animated.group>
          <mesh
            name="link_1"
            geometry={nodes.link_1.geometry}
            material={materials.fanuc_yellow}
          />
        </animated.group>
      </group>
    </group>
  )
}
