/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { animated } from "@react-spring/three"
import { useGLTF } from "@react-three/drei"
import type { RobotModelProps } from "./types"

FANUC_LR_MATE_200iD7L.config = {
  rotationOffsets: [0, Math.PI / 2, 0, 0, 0, 0],
}

export function FANUC_LR_MATE_200iD7L({ modelURL, ...props }: RobotModelProps) {
  const { nodes, materials } = useGLTF(modelURL) as any
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="link_0">
          <mesh
            name="visuals_0"
            geometry={nodes.visuals_0.geometry}
            material={materials.fanuc_metal_black}
          />
          <mesh
            name="visuals_0_1"
            geometry={nodes.visuals_0_1.geometry}
            material={materials.fanuc_metal_black}
          />
          <mesh
            name="visuals_0_2"
            geometry={nodes.visuals_0_2.geometry}
            material={materials.fanuc_aluminium_black}
          />
        </group>
        <animated.group name="FANUC_LRMATE200ID7L_J00">
          <animated.group
            name="FANUC_LRMATE200ID7L_J01"
            position={[0.05, 0, 0]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          >
            <animated.group
              name="FANUC_LRMATE200ID7L_J02"
              position={[0.44, 0, 0]}
            >
              <animated.group
                name="FANUC_LRMATE200ID7L_J03"
                position={[0.035, 0, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <animated.group
                  name="FANUC_LRMATE200ID7L_J04"
                  position={[0, -0.42, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <animated.group
                    name="FANUC_LRMATE200ID7L_J05"
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <animated.group
                      name="FANUC_LRMATE200ID7L_FLG"
                      position={[0, -0.08, 0]}
                      rotation={[-Math.PI, 0, 0]}
                    />
                    <mesh
                      name="link_6"
                      geometry={nodes.link_6.geometry}
                      material={materials.fanuc_metal_black}
                      position={[-0.475, 0.47, 0]}
                      rotation={[0, 0, -Math.PI / 2]}
                    />
                  </animated.group>
                  <group
                    name="link_5"
                    position={[-0.475, 0, -0.47]}
                    rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  >
                    <mesh
                      name="visuals_5"
                      geometry={nodes.visuals_5.geometry}
                      material={materials.fanuc_yellow}
                    />
                    <mesh
                      name="visuals_5_1"
                      geometry={nodes.visuals_5_1.geometry}
                      material={materials.fanuc_stainless_steel}
                    />
                    <mesh
                      name="visuals_5_2"
                      geometry={nodes.visuals_5_2.geometry}
                      material={materials.fanuc_metal_black}
                    />
                  </group>
                </animated.group>
                <group
                  name="link_4"
                  position={[-0.475, 0.05, 0]}
                  rotation={[0, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="visuals_4"
                    geometry={nodes.visuals_4.geometry}
                    material={materials.fanuc_yellow}
                  />
                  <mesh
                    name="visuals_4_1"
                    geometry={nodes.visuals_4_1.geometry}
                    material={materials.fanuc_aluminium_black}
                  />
                </group>
              </animated.group>
              <group
                name="link_3"
                position={[-0.44, 0, -0.05]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              >
                <mesh
                  name="visuals_3"
                  geometry={nodes.visuals_3.geometry}
                  material={materials.fanuc_yellow}
                />
                <mesh
                  name="visuals_3_1"
                  geometry={nodes.visuals_3_1.geometry}
                  material={materials.fanuc_stainless_steel}
                />
              </group>
            </animated.group>
            <mesh
              name="link_2"
              geometry={nodes.link_2.geometry}
              material={materials.fanuc_yellow}
              position={[0, 0, -0.05]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            />
          </animated.group>
          <group name="link_1">
            <mesh
              name="visuals_1"
              geometry={nodes.visuals_1.geometry}
              material={materials.fanuc_yellow}
            />
            <mesh
              name="visuals_1_1"
              geometry={nodes.visuals_1_1.geometry}
              material={materials.fanuc_stainless_steel}
            />
          </group>
        </animated.group>
      </group>
    </group>
  )
}
